
CREATE TABLE MOVIE
(
  UNIQUE_ID   VARCHAR(200) NOT NULL COMMENT '영화이름 대표값',
  MOVIE_TITLE VARCHAR(200) NOT NULL COMMENT '영화이름',
  GENRE       VARCHAR(200) NOT NULL COMMENT '장르',
  PRIMARY KEY (UNIQUE_ID)
);

CREATE TABLE POSTER
(
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '포스터목록 대표값',
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '영화이름 대표값'
);

CREATE TABLE POSTER_LIST
(
  POSTER    VARCHAR(200) NULL     COMMENT '포스터',
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '포스터목록 대표값',
  PRIMARY KEY (UNIQUE_ID)
);

CREATE TABLE RENT
(
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '영화이름 대표값',
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '사용자 대표값'
);

CREATE TABLE RENTER
(
  NAME      VARCHAR(200) NOT NULL COMMENT '이름',
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '사용자 대표값',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '대여자';

ALTER TABLE RENT
  ADD CONSTRAINT FK_MOVIE_TO_RENT
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES MOVIE (UNIQUE_ID);

ALTER TABLE RENT
  ADD CONSTRAINT FK_RENTER_TO_RENT
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES RENTER (UNIQUE_ID);

ALTER TABLE POSTER
  ADD CONSTRAINT FK_POSTER_LIST_TO_POSTER
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES POSTER_LIST (UNIQUE_ID);

ALTER TABLE POSTER
  ADD CONSTRAINT FK_MOVIE_TO_POSTER
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES MOVIE (UNIQUE_ID);
